# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
-   repo: local
    hooks:
    -   id: uv-sync
        name: uv sync
        entry: uv sync
        language: system
        types: [python]
        pass_filenames: false
    -   id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: false
    -   id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types: [python]
    -   id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: 37b5f0 # main 2025/05/17
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
- repo: https://github.com/hollow/pre-commit-actionlint
  rev: "v1.6.24"
  hooks:
    - id: actionlint
default_install_hook_types:
  - pre-commit
  - commit-msg
