volumes:
  db:
services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      PGDATA: /data/pg
      POSTGRES_PASSWORD: dev_password
      POSTGRES_USER: project_manager
      POSTGRES_DB: project_manager
