"""add deleted column

Revision ID: 00006
Revises: 00005
Create Date: 2025-07-19 22:41:14.864769

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00006"
down_revision: str | Sequence[str] | None = "00005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource", sa.Column("deleted", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_resource_deleted"), "resource", ["deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resource_deleted"), table_name="resource")
    op.drop_column("resource", "deleted")
    # ### end Alembic commands ###
