"""new-revision

Revision ID: 00000
Revises:
Create Date: 2025-11-02 23:40:38.627872

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "00000"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
