"""foo

Revision ID: 00002
Revises: 00001
Create Date: 2025-11-02 23:55:00.370010

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "00002"
down_revision: str | Sequence[str] | None = "00001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
