"""foo

Revision ID: 00001
Revises: 00000
Create Date: 2025-11-02 23:52:31.505333

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "00001"
down_revision: str | Sequence[str] | None = "00000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
