[project]
name = "example"
readme = "README.md"
version = "0.0.12-rc.5"
dependencies = ["brewing[postgresql]"]
requires-python = ">=3.14"

[project.entry-points.brewing]
example = "example.app:app"


[project.urls]
Homepage = "https://mikemcowie.github.io/brewing/"
Documentation = "https://mikemcowie.github.io/brewing/"
Repository = "https://github.com/mikemcowie/brewing"
Issues = "https://github.com/mikemcowie/brewing"
Releases = "https://github.com/mikemcowie/brewing/releases"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["brewing[testing]", "pytest"]
