name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - 4-publish-prereleases-to-pypi-on-every-merge # TODO - remove
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      #- name: Install UV
      #  uses: astral-sh/setup-uv@v6

      #- name: run pre-commit
      #  run: uv run pre-commit run --all-files

      #- name: run pytest
      #  run: uv run pytest -v

      #- name: ensure docs build
      #  run: make docs-build

  docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    environment: github-pages
    permissions:
      pages: write
      id-token: write
    needs:
    - test
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: build docs
        run: make docs-build

      - name: Create artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == '4-publish-prereleases-to-pypi-on-every-merge' # TODO - revert to main
    needs:
    - test
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Make a release
        run: uv run scripts/manage_project.py release

  publish:
    name: Publish
    needs:
    - release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == '4-publish-prereleases-to-pypi-on-every-merge' # TODO - revert to main

    environment:
      name: test-pypi
      url: https://testpypi.org/p/brewing

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Publish distribution
        run: uv run scripts/manage_project.py publish
